### ISSUE TITLE
Can't install rtags 2.11 from tarball due to missing rct/json/json.hpp

### ISSUE THREAD

**Issue by kain88-de** [Andersbakken/rtags#1014]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Can't install rtags 2.11 with `M-x install-rtags` currently. I installed rtags from melpa.

#### Expected behavior
Installation without a problem. This used to work for the last release.

#### Actual behavior
The compilation terminates due to missing dependencies of rct. I checked the source that rtags.el downloads. The file is indeed missing from the tarball.

```
Scanning dependencies of target rtags
[  1%] Building CXX object src/CMakeFiles/rtags.dir/ClangIndexer.cpp.o
[  2%] Building CXX object src/CMakeFiles/rtags.dir/ClangThread.cpp.o
[  3%] Building CXX object src/CMakeFiles/rtags.dir/ClassHierarchyJob.cpp.o
[  5%] Building CXX object src/CMakeFiles/rtags.dir/CompilerManager.cpp.o
[  6%] Building CXX object src/CMakeFiles/rtags.dir/CompletionThread.cpp.o
/home/max/Downloads/rtags-2.11/src/CompletionThread.cpp:27:29: fatal error: rct/json/json.hpp: No such file or directory
 #include "rct/json/json.hpp"
                             ^
compilation terminated.
src/CMakeFiles/rtags.dir/build.make:158: recipe for target 'src/CMakeFiles/rtags.dir/CompletionThread.cpp.o' failed
make[2]: *** [src/CMakeFiles/rtags.dir/CompletionThread.cpp.o] Error 1
CMakeFiles/Makefile2:380: recipe for target 'src/CMakeFiles/rtags.dir/all' failed
make[1]: *** [src/CMakeFiles/rtags.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
```

### Environment
- Your operating system:
Fedora 25

- LLVM/Clang version:

```
thinki src/rct » clang --version
clang version 3.9.1 (tags/RELEASE_391/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### Feature request

Please keep older tarballs on your github.io page around.

**Comment by FinnG** [comment]
I can't build from source due to this issue either (I was retesting #996).

**Comment by Andersbakken** [comment]
Should be fixed now. I had a bug in my release cron job. Thanks.

**Comment by FinnG** [comment]
I'm still seeing this issue when building direct from the git repo.

**Comment by kain88-de** [comment]
Thanks for fixing it so quickly. Do you know when the cdn updates the tarball on your website? I still get the same error currently.

**Comment by kain88-de** [comment]
Sorry my fault. I needed to remove the old faulty download of the tarbal.

**Comment by Aar0nB** [comment]
I also still have this issue with git repo. It would be great if this would be fixed. Thank you very much.

**Comment by afarmr** [comment]
made it work by explicitly cloning rct branch, build fine now.

**Comment by FinnG** [comment]
Ahh great, I'll try that. Thanks :)

**Comment by Andersbakken** [comment]
Another options is:

git clone ...rtags.git
cd rtags
git submodule init
git submodule update

regards

Anders
