### ISSUE TITLE
Rdm crashes frequently on CentOS 7.4

### ISSUE THREAD

**Issue by swarnendubiswas** [Andersbakken/rtags#1094]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Describe briefly the problem.
Rdm crashes frequently on my CentOS 7.4 workstation.

#### Expected behavior
Describe what you expected to happen.
Rdm session should not crash (at least as frequently).

#### Actual behavior
Describe what actually happened.
Some logs:

handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstdlib:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/bits/algorithmfwd.h:35:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cmath:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstdio:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstdlib:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstdlib:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/csignal:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstring:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cmath:41:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstdint:38:1
handleInclude failed (nil) inclusion directive include bits/c++config.h /../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstdio:41:1
Fixit for /usr/include/c++/4.8.2/bits/memoryfwd.h:50:43: Insert ";"
Fixit for /usr/include/c++/4.8.2/bits/memoryfwd.h:50:43: Insert ";"

/workspace/sbiswas/github/rtags/build/bin/rc --current-file=/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp -b -z --verify-version=124 -U /workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp:1459:16: --elisp -K
/workspace/sbiswas/github/rtags/build/bin/rc -m --elisp
/workspace/sbiswas/github/rtags/build/bin/rc --current-file=/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp -b -z --verify-version=124 -f /workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp:1459:16: --all-targets
/workspace/sbiswas/github/rtags/build/bin/rc --current-file=/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp -b -z --verify-version=124 --current-project
/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../include/c++/4.8.5/cstdio:41:10: fatal error: 'bits/c++config.h' file not found
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:51:5: error: use of undeclared identifier 'clock_gettime'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:75:10: error: no type named 'ostream' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:75:37: error: no member named 'cout' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:76:10: error: no type named 'ofstream' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:77:5: error: use of undeclared identifier '__assert_fail'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:78:5: error: use of undeclared identifier '__assert_fail'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:79:5: error: use of undeclared identifier '__assert_fail'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:80:5: error: use of undeclared identifier '__assert_fail'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:87:14: error: no member named 'cerr' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:87:48: error: no member named 'endl' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:103:10: error: no member named 'cout' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:104:10: error: no member named 'cerr' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:108:10: error: no member named 'cerr' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:108:82: error: no member named 'endl' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:140:24: error: no member named 'endl' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:141:26: error: no member named 'ios' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:141:43: error: no member named 'ios' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:154:14: error: no member named 'cerr' in namespace 'std'
/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/src/benchmark.cpp:154:74: error: no member named 'endl' in namespace 'std'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/workspace/sbiswas/github/rtags/build/bin/rc --current-file=/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp -b --unsaved-file=/workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp:63617 -z --verify-version=124 --code-complete-at /workspace/sbiswas/iss-workspace/proteus/slambench-bitbucket/kfusion/include/control.hpp:60:5: --synchronous-completions --elisp --code-complete-prefix=PRO
Caught signal 11
rdm[0x4589ca]
/lib64/libpthread.so.0(+0xf5e0)[0x7fe9db1d95e0]
rdm[0x5a75bc]
rdm(_ZN7Project20isTemplateDiagnosticERKSt4pairI8Location10DiagnosticE+0x46)[0x5aa366]
rdm(_ZN7Project17updateDiagnosticsEjRK3MapI8Location10DiagnosticSt4lessIS1_EE+0x393)[0x5aaff3]
rdm(_ZN16CompletionThread18processDiagnosticsEPKNS_7RequestEP21CXCodeCompleteResultsP21CXTranslationUnitImpl+0x356)[0x5572c6]
rdm(_ZN16CompletionThread7processEPNS_7RequestE+0x1c36)[0x55a866]
rdm(_ZN16CompletionThread3runEv+0x7a8)[0x55cbb8]
rdm(_ZN6Thread10localStartEPv+0x29)[0x50af89]
/lib64/libpthread.so.0(+0x7e25)[0x7fe9db1d1e25]
/lib64/libc.so.6(clone+0x6d)[0x7fe9d9f6434d]

### Environment
- Your operating system: CentOS 7.4

- LLVM/Clang version: 5.0

I built RTags with the following flags: 
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/workspace/sbiswas/software/llvm/llvm.install/bin/llvm-config -DCMAKE_INSTALL_PREFIX=/workspace/sbiswas/github/rtags/build ..

Should I build LLVM with assertions disabled? I am not sure whether the problem is because of that.

### Feature request

Describe the feature we should add to **RTags**.

**Comment by collinjackson93** [comment]
I saw something similar when I built clang 5 from their svn repo. When you run rdm,  one of the lines it initially outputs is the include path. Can you post that here? Also, can you post the output from `llvm-config --version`?

**Comment by amosbird** [comment]
I also saw this when using clang 5 and clang 6.

**Comment by swarnendubiswas** [comment]
`llvm-config --version` gives 3.4.2, and the include path also seems correct `Includepaths: "-isystem" /workspace/sbiswas/software/llvm/llvm.install/lib/clang/5.0.0/include/`

**Comment by amosbird** [comment]
@swarnendubiswas I've resolved a similar issue https://github.com/Andersbakken/rtags/issues/1095 . Maybe it can help you out :-)

**Comment by sambrightman** [comment]
I been seeing this for a while on clang 4.0.1, `llvm-config --version` gives 4.0.1. I have `Includepaths: "-isystem" /spare/local/environ-asgard/llvm/4.0.1/lib/clang/4.0.1/include/`. I've tried wiping the cache. I pass `-std=c++14` to clang in my build/`compile_commands.json`

**Comment by swarnendubiswas** [comment]
@amosbird Thanks, I am trying it out. Let us see!

**Comment by BenjaminNavarro** [comment]
I think I have the same issue on Archlinux. 

I have `llvm-config --version = 5.0.0` and `Includepaths: "-isystem" /usr/lib/clang/5.0.0/include/`

But when I run `rdm --clean-slate`, index some compilation database and ask for completions (through atm-rtags-plus within Atom), `rdm` crashes in some cases. I ran `rdm` with Valgrind and here is the log part related to the crash:

```
==3989== Thread 3:
==3989== Invalid read of size 8
==3989==    at 0x2CE063: ??? (in /usr/bin/rdm)
==3989==    by 0x2D2D25: Project::isTemplateDiagnostic(std::pair<Location, Diagnostic> const&) (in /usr/bin/rdm)
==3989==    by 0x2D341B: Project::updateDiagnostics(unsigned int, Map<Location, Diagnostic, std::less<Location> > const&) (in /usr/bin/rdm)
==3989==    by 0x2728A7: CompletionThread::processDiagnostics(CompletionThread::Request const*, CXCodeCompleteResults*, CXTranslationUnitImpl*) (in /usr/bin/rdm)
==3989==    by 0x276533: CompletionThread::process(CompletionThread::Request*) (in /usr/bin/rdm)
==3989==    by 0x2794FE: CompletionThread::run() (in /usr/bin/rdm)
==3989==    by 0x224FF4: Thread::localStart(void*) (in /usr/bin/rdm)
==3989==    by 0x6E35089: start_thread (in /usr/lib/libpthread-2.26.so)
==3989==    by 0x7AC447E: clone (in /usr/lib/libc-2.26.so)
==3989==  Address 0x40 is not stack'd, malloc'd or (recently) free'd
==3989== 
Caught signal 11
rdm(+0x5cd1f)[0x164d1f]
/usr/lib/libpthread.so.0(+0x11da0)[0x6e3fda0]
/usr/lib/libpthread.so.0(raise+0xee)[0x6e3fc1e]
/usr/lib/../lib/libLLVM-5.0.so(+0x77f18a)[0x870918a]
/usr/lib/libpthread.so.0(+0x11da0)[0x6e3fda0]
rdm(+0x1c6063)[0x2ce063]
rdm(_ZN7Project20isTemplateDiagnosticERKSt4pairI8Location10DiagnosticE+0x46)[0x2d2d26]
rdm(_ZN7Project17updateDiagnosticsEjRK3MapI8Location10DiagnosticSt4lessIS1_EE+0x55c)[0x2d341c]
rdm(_ZN16CompletionThread18processDiagnosticsEPKNS_7RequestEP21CXCodeCompleteResultsP21CXTranslationUnitImpl+0x628)[0x2728a8]
rdm(_ZN16CompletionThread7processEPNS_7RequestE+0x1824)[0x276534]
rdm(_ZN16CompletionThread3runEv+0x10af)[0x2794ff]
rdm(_ZN6Thread10localStartEPv+0x25)[0x224ff5]
/usr/lib/libpthread.so.0(+0x708a)[0x6e3508a]
/usr/lib/libc.so.6(clone+0x3f)[0x7ac447f]
```

**Comment by sambrightman** [comment]
I mis-spoke; I'm still getting the problem with extra include paths configured:

```rdm[0x45ebda]
/lib64/libpthread.so.0(+0xf7e0)[0x7f9229b737e0]
rdm(_ZNSt10_HashtableIjSt4pairIKjSt10shared_ptrI7FileMapI8Location6SymbolEEESaIS8_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENSA_18_Mod_range_hashingENSA_20_Default_ranged_hashENSA_20_Prime_rehash_policyENSA_17_Hashtable_traitsILb0ELb0ELb1EEEE4findERS1_+0x4)[0x5a3d34]
rdm[0x5bc505]
rdm(_ZN7Project20isTemplateDiagnosticERKSt4pairI8Location10DiagnosticE+0x46)[0x5c8106]
rdm(_ZN7Project17updateDiagnosticsEjRK3MapI8Location10DiagnosticSt4lessIS1_EE+0x43b)[0x5c86db]
rdm(_ZN16CompletionThread18processDiagnosticsEPKNS_7RequestEP21CXCodeCompleteResultsP21CXTranslationUnitImpl+0x556)[0x5668c6]
rdm(_ZN16CompletionThread7processEPNS_7RequestE+0x29c4)[0x56ba84]
rdm(_ZN16CompletionThread3runEv+0x123)[0x56cc63]
rdm(_ZN6Thread10localStartEPv+0x25)[0x51d425]
/lib64/libpthread.so.0(+0x7aa1)[0x7f9229b6baa1]
/lib64/libc.so.6(clone+0x6d)[0x7f9228a20bcd]
```

**Comment by Andersbakken** [comment]
This should be fixed now I think.

**Comment by sambrightman** [comment]
Still crashing for me. I think there may be more than one issue, as I've seen a different trace in debug mode:

```
Thread 1 "rdm" received signal SIGPIPE, Broken pipe.
0x00007ffff78517cd in write () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff78517cd in write () from /lib64/libpthread.so.0
#1  0x0000000000514590 in SocketClient::writeTo (this=0x1686520, host=..., port=port@entry=0, f_data=0x15fe018 "\v", size=10) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/SocketClient.cpp:507
#2  0x0000000000514f18 in SocketClient::write (this=<optimized out>, data=<optimized out>, size=<optimized out>) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/SocketClient.cpp:569
#3  0x00000000004f823c in SocketClient::write (data=..., this=<optimized out>) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/SocketClient.h:60
#4  Connection::send (this=0x15f54e0, message=...) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/Connection.cpp:225
#5  0x00000000004893e1 in Server::handleVisitFileMessage (this=this@entry=0x878ca0, message=std::shared_ptr (count 3, weak 0) 0x17af3a0, conn=std::shared_ptr (count 3, weak 2) 0x15f54e0)
    at /apps/homefs1/sbrightman/dev/rtags/src/Server.cpp:2013
#6  0x0000000000499a66 in Server::onNewMessage (this=0x878ca0, message=..., connection=std::shared_ptr (count 3, weak 2) 0x15f54e0) at /apps/homefs1/sbrightman/dev/rtags/src/Server.cpp:394
#7  0x00000000004f5ee3 in std::function<void (std::shared_ptr<Message>, std::shared_ptr<Connection>)>::operator()(std::shared_ptr<Message>, std::shared_ptr<Connection>) const (
    __args#1=std::shared_ptr (count 9745216, weak -1) 0x7fffffff6b30, __args#0=std::shared_ptr (count 28702608, weak -1) 0x7fffffff6b10, this=<optimized out>) at /spare/local/environ-asgard/gcc/5.4.0/include/c++/5.4.0/functional:2267
#8  Signal<std::function<void (std::shared_ptr<Message>, std::shared_ptr<Connection>)> >::operator()<std::shared_ptr<Message>&, std::shared_ptr<Connection>&>(std::shared_ptr<Message>&, std::shared_ptr<Connection>&) (this=0x15f5558)
    at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/SignalSlot.h:70
#9  Connection::onDataAvailable (this=0x15f54e0, client=..., buf=...) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/Connection.cpp:154
#10 0x0000000000516df9 in std::function<void (std::shared_ptr<SocketClient> const&, Buffer&&)>::operator()(std::shared_ptr<SocketClient> const&, Buffer&&) const (__args#1=..., __args#0=..., this=0x18164d8)
    at /spare/local/environ-asgard/gcc/5.4.0/include/c++/5.4.0/functional:2267
#11 Signal<std::function<void (std::shared_ptr<SocketClient> const&, Buffer&&)> >::operator()<std::shared_ptr<SocketClient>&, Buffer>(std::shared_ptr<SocketClient>&, Buffer&&) (this=0x1686560)
    at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/SignalSlot.h:70
#12 SocketClient::socketCallback (this=0x1686520, f=<optimized out>, mode=1) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/SocketClient.cpp:676
#13 0x00000000004fef60 in std::function<void (int, unsigned int)>::operator()(int, unsigned int) const (__args#1=1, __args#0=30, this=0x7fffffffb2a0) at /spare/local/environ-asgard/gcc/5.4.0/include/c++/5.4.0/functional:2267
#14 EventLoop::fireSocket (this=this@entry=0x8792f0, fd=30, mode=1) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/EventLoop.cpp:710
#15 0x00000000004ffd59 in EventLoop::processSocketEvents (this=this@entry=0x8792f0, events=events@entry=0x7fffffffb500, eventCount=<optimized out>) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/EventLoop.cpp:851
#16 0x0000000000501a8a in EventLoop::exec (this=0x8792f0, timeoutTime=timeoutTime@entry=-1) at /apps/homefs1/sbrightman/dev/rtags/src/rct/rct/EventLoop.cpp:964
#17 0x000000000045c966 in main (argc=<optimized out>, argv=<optimized out>) at /apps/homefs1/sbrightman/dev/rtags/src/rdm.cpp:865

```

**Comment by brycethomas** [comment]
I also ran into the "handleInclude failed (nil) inclusion directive include" issue with Clang 6.0.0.

> @swarnendubiswas I've resolved a similar issue #1095 . Maybe it can help you out :-)

^The workaround here worked for me.  Specifically, the instructions in https://github.com/Andersbakken/rtags/issues/1095#issuecomment-345903555.
