### ISSUE TITLE
Master build does not complete fully

### ISSUE THREAD

**Issue by mckellyln** [Andersbakken/rtags#1225]
Summary:
Latest master build does not complete fully

steps to reproduce:
git pull
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
make

Env:
Linux 4.15.0-33-generic #36\~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(Ubuntu 16.04 with latest HWE kernel)
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
libclang-3.8.so.1 => /usr/lib/llvm-3.8/lib/libclang-3.8.so.1 (0x0000150db0e77000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x0000150db0af5000)
libLLVM-3.8.so.1 => /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1 (0x0000150dacff6000)
GNU Emacs 24.5.1

Symptom:
[ 86%] Creating byte-compiled Emacs lisp /home/kellma02/Downloads/rtags/build/src/helm-rtags.elc
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50global.el (source)...
Required feature `cl-seq' was not provided
src/CMakeFiles/emacs_byte_compile_helm-rtags.el.dir/build.make:60: recipe for target 'src/helm-rtags.elc' failed
make[2]: *** [src/helm-rtags.elc] Error 255
CMakeFiles/Makefile2:1244: recipe for target 'src/CMakeFiles/emacs_byte_compile_helm-rtags.el.dir/all' failed

Thank you for rtags and for any suggestions here.

**Comment by mckellyln** [comment]
Should I try:
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DRTAGS_NO_ELISP_BYTECOMPILE=1 ..

**Comment by Andersbakken** [comment]
It should be fixed now. Sorry. It was a typo.

**Comment by owenst** [comment]
@Andersbakken I'm still getting this error on a fresh clone with a nearly identical setup. I tried installing the new package through emacs and also cloning directly from git. Same error both times. 



Description:	Ubuntu 16.04.5 LTS
linux kernel: 4.15.0-33-generic
x86_64 GNU/Linux
GNU Emacs 24.5.1
libclang 3.8.0

From git clone during make:

[ 85%] Built target rdm
[ 86%] Creating byte-compiled Emacs lisp /home/trevor/.emacs.d/rtags/build/src/helm-rtags.elc
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Required feature `cl-seq' was not provided
src/CMakeFiles/emacs_byte_compile_helm-rtags.el.dir/build.make:60: recipe for target 'src/helm-rtags.elc' failed
make[2]: *** [src/helm-rtags.elc] Error 255
CMakeFiles/Makefile2:1239: recipe for target 'src/CMakeFiles/emacs_byte_compile_helm-rtags.el.dir/all' failed
make[1]: *** [src/CMakeFiles/emacs_byte_compile_helm-rtags.el.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

From emacs:
Compiling file ~/.emacs.d/elpa/rtags-20180909.1749/rtags-pkg.el at Sun Sep  9 22:00:17 2018
Entering directory `~/.emacs.d/elpa/rtags-20180909.1749/'

Compiling file ~/.emacs.d/elpa/rtags-20180909.1749/rtags.el at Sun Sep  9 22:00:17 2018
rtags.el:44:1:Error: Required feature `cl-seq' was not provided


According to https://www.gnu.org/software/emacs/manual/html_mono/cl.html
"
1.1 Usage
This package is distributed with Emacs, so there is no need to install any additional files in order to start using it. Lisp code that uses features from this package should simply include at the beginning:

     (require 'cl-lib)
"
