### ISSUE TITLE
There is no 2.41 release in Releases in this repository

### ISSUE THREAD

**Issue by SL-RU** [Andersbakken/rtags#1409]
**Describe the bug**
I've installed rtags from elpa using package-install rtags. RTags version is 2.41 
And `rtags-install`  results the message:
```
Downloading rtags from https://github.com/Andersbakken/rtags/releases/download/v2.41/rtags-2.41.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     23      0 --:--:-- --:--:-- --:--:--    23
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to untar rtags-2.41.tar.bz2
```

**To Reproduce**
1. `package-install` `rtags` 
2. `rtags-install`

**Expected behavior**
Download and compile rtags

**Environment (please complete the following information):**
 - OS/Version: Arch Linux
 - RTags(rdm,rc): 2.41
 - Emacs: 27.1
 - LLVM/Clang: 11.1.0

**Additional context**
There is no tag and release 2.41 in Releases here

**Comment by SL-RU** [comment]
I've fixed issue just editing value of `rtags-package-version` to `2.38` in rtags.el and `M-x byte-recompile-directory`. You need to make a new release in this repository

**Comment by Thaodan** [comment]
The new release should be tagged if it is not just a bump for the next version.

**Comment by jarcode-foss** [comment]
The `2.41` release still isn't tagged correctly (nor is `2.39` or `2.40`).

**Comment by t-e-r-m** [comment]
Going to bump this, still an issue.

Github returns 404 for the following:
https://github.com/Andersbakken/rtags/releases/download/v2.41/rtags-2.41.tar.bz2

**Comment by avlec** [comment]
Still an issue in 2022

**Comment by Andersbakken** [comment]
Sorry about this. These notifications ended up in a place where I didn't read them. I've pushed the v2.41 tag now.
