### ISSUE TITLE
Rtags cache gets corrupted?

### ISSUE THREAD

**Issue by pradhanpk** [Andersbakken/rtags#342]
On some rtags restarts, I see an error in the log which looks like this:

```
Error during validation: /some/file/in/repo (2) 73 /path/to/rtags/cache
852/symnames
```
The memory usage of rtags during such runs would be a small fraction of what it usually takes. Reading the compilation db with rc -J ends up successfully parsing around 1% of the sources and fails for the rest with error statements like:

```
Holding off on /some/source/file.cpp it's got a header error from /some/header/file.h
```

Restarting rtags, without deleting the cache, does not help. On deleting the cache folder, it finds all sources and gets back to normal.

**Comment by pradhanpk** [comment]
Shoe-horning another issue here - if you had an emacs sessions open with `rtags-diagnostics` running, then kill and restart `rdm`, call `rc -J` and restart `rtags-diagnostics` while `rdm` is still parsing sources, the `*RTags Raw*` buffer sometimes ends up with invalid lisp expressions, leading to a LOT of `eval` failures. `toggle-debug-on-error` didn't give me a backtrace somehow, but I could see that the lisp expressions were invalid. So, the likely error location is the `(eval (read (current-buffer)))` call in `rtags-parse-diagnostics`.

**Comment by Andersbakken** [comment]
Hi Pradhan

I've been chasing both of these bugs. Does the diagnostics issue reliably
reproduce for you? That would be nice.

I'll try to fix both issues as soon as I can.

Anders

**Comment by pradhanpk** [comment]
@Andersbakken Just tried and failed to reproduce the diagnostics issue. Please let me know how I can help with either of the issues.

**Comment by JunfengJia** [comment]
I'm run into this bug consistently.
The bug in my PC is the Failed to open .rtags/___project_path___/number/usrs          /___project_path___/a.c (2) 70

the "number" folder is not existing, don't know why. I guess this caused some editor save by rename?
How about recreate this file's index if the folder not found?

**Comment by jmdaly** [comment]
I'm also experiencing this issue quite regularly (several times per work day). Apart from this issue, I'm loving using rtags! Is there anything I can do to help in terms of providing some debug output or anything like that?

**Comment by saxena84** [comment]
Hi, I saw this issue too (same as mentioned by @JunfengJia ).
The "number" folder (`59` in my case) didn't exist. There were, however, folders with names `59[0-9]`.
I did *not* restart the rdm daemon in-between.

```
$ rdm --version
2.0.67
```

```
$ rc --version
2.0.67
```

PS: rtags is awesome!

**Comment by philippe-grenet** [comment]
I too see the same error as  @JunfengJia and @saxena84 . The stack trace is:

```
Debugger entered--Lisp error: (void-variable FILENAME)
  (list 5 27 nil (quote error) "expected " FILENAME " or \"FILENAME\" or <FILENAME>")
  (list (list 5 27 nil (quote error) "expected " FILENAME " or \"FILENAME\" or <FILENAME>"))
  (cons "/a/long/path/to/mbsq_dataeventbuilder.t.cpp" (list (list 5 27 nil (quote error) "expected " FILENAME " or \"FILENAME\" or <FILENAME>")))
  (list (quote checkstyle) (cons "/a/long/path/to/mbsq_dataeventbuilder.t.cpp" (list (list 5 27 nil (quote error) "expected " FILENAME " or \"FILENAME\" or <FILENAME>"))))
  eval((list (quote checkstyle) (cons "/a/long/path/to/mbsq_dataeventbuilder.t.cpp" (list (list 5 27 nil (quote error) "expected " FILENAME " or \"FILENAME\" or <FILENAME>")))))
  rtags-parse-diagnostics()
  rtags-diagnostics-process-filter(#<process RTags Diagnostics> "(list 'checkstyle (cons \"/a/long/path/to/mbsq_dataeventbuilder.t.cpp\" (list (list 234 2 1582 'skipped \"\"))))\n")
```

(I have replaced the file path for clarity)

The content of buffer RTags Raw is this:

```
(list 'checkstyle (cons "/a/long/path/to/mbsq_dataeventbuilder.t.cpp" (list (list 5 27 nil 'error "expected "FILENAME" or \"FILENAME\" or <FILENAME>"))))(list 'checkstyle (cons "/a/long/path/to/mbsq_dataeventbuilder.cpp" (list (list 145 5 2 'warning "expression result unused") (list 145 7 nil 'fixit "expected ';' after expression"))))
```

Hope it helps.

**Comment by Andersbakken** [comment]
Hi Guys. 

Sorry about the delay. I believe I've fixed the diagnostics issue now. Can you verify?

**Comment by pradhanpk** [comment]
@Andersbakken I ran into the `rtags-diagnostics` parse errors on restarting with the update. Haven't yet run into the cache issue.

**Comment by JunfengJia** [comment]
I meet it again after update and re-create my project, I used vim. The chance is very low than before, but still exist.

**Comment by Nephyrin** [comment]
I'm still occasionally seeing the cache corruption -- it may be related to having two instances of emacs running, as a guess. I have not seen it when that is not the case.

**Comment by Andersbakken** [comment]
There is a bug in there. I see it occasionally too but I can't find a good
way to repro. Don't really see why two emacses should trigger it but if you
find a way to reliably make it happen I'd love to hear it.

I'm also occasionally hitting the diagnostics error. No idea what makes it
happen but I'd love a way to repro that too.

Anders

**Comment by Andersbakken** [comment]
Closing until someone can find a consistent repro. I haven't actually seen it in a while.

**Comment by Wintaru** [comment]
Just chiming in that I'm seeing this too in Debian. Unfortunately I too am unable to provide a consistent way to reproduce it, but I'll try to keep an eye on it. Blowing out my ~/.rtags dir and rerunning rc -J seems to have resolved it for now.

**Comment by jmdaly** [comment]
@Wintaru I used to see this issue with rtags quite frequently, but since I started building rtags with a recent version of clang (3.7), the issue has gone away for me. I'm not sure if it's directly related, but it might be something to try.

I've written a script for myself to download, build, and install rtags with the latest release of clang, on Ubuntu 14.04,  [here](https://raw.githubusercontent.com/jmdaly/system-setup-scripts/master/install_rtags.sh). Hope it might help.
