### ISSUE TITLE
'rc -T .' incorrect result, maybe similar with #798 

### ISSUE THREAD

**Issue by sunlin7** [Andersbakken/rtags#803]
Hi,

`rc -T .` give incorrect result, maybe similar with #798, 

```
/tmp$ rc -w
/home/sunline/tmp/clang-parse/ <=
/tmp$ rc -T .
managed
```

Best Regards

**Comment by Andersbakken** [comment]
I think it should be fixed now. Can you check?

regards

Anders

**Comment by sunlin7** [comment]
Hi,
I didn't see you commit for this issue.
Actually, I upgrade your commits for #798, verify the #798,  it's fixed. 
And then I try `rc -T` , find this issue and report to you.
So this issue still there. :)

**Comment by sunlin7** [comment]
Close this ticket without no response for long time. thank you.
